### ISSUE TITLE
Animated from-to Line, Marker from Geocoder

### ISSUE THREAD

**Issue by SunStormRain** [HsKA-OSGIS/GalaXYZ#15]
From-to Line is not added, if two markers origin from Geocoder result.
(1st marker from Geocoder + 2nd manually works, but not other way around)

**Comment by enocholumide** [comment]
I will take a look. Perhaps give me a screen shot of what is going on.

**Comment by SunStormRain** [comment]
![bug15](https://user-images.githubusercontent.com/26673072/33806182-5ae66de8-ddc4-11e7-9bc3-3ca30c1b1395.png)

**Comment by enocholumide** [comment]
I ll take a look in a moment. 

Is your branch up to date with master?

**Comment by SunStormRain** [comment]
Yes, take your time.
